### ISSUE TITLE
UUIDs for every communicated field

### ISSUE THREAD

**Issue by croqueGrec09** [openlibraryenvironment/gokb#111]
Concerns now mainly Coverages and Identifiers.
As there is a 1:n relation between TitleInstances/Packages/Orgs <-> Identifiers and TitleInstancePackagePlatform <-> Coverages, we may have different counts in the respective GOKb and LAS:eR sets, e.g. a LAS:eR TIPP (or IssueEntitlement) has two coverage statements, the respective GOKb TIPP only one. How do we determine which one of the entires has to be deleted and which updated? Currently, the sync process guesses the equivalent entry, but for long term, such objects need UUIDs.

**Comment by darupp** [comment]
Not feasible for identifiers because ids are immutable in GOKb, therefore changing an identifier means linking another identifier object. 

Possible for coverages, but there are problems

  * UID is a field of kb_component, so every component inherits this field. Coverage doesn't inherit from component, so the concept of UID has to be changed

This would be too much, so the suggestion is, that other systems replace all coverages on a tipp as a whole.
