### ISSUE TITLE
View Create Title: Search title

### ISSUE THREAD

**Issue by dirk-ecker** [openlibraryenvironment/gokb#152]
### Description
The view contains an title field. The title the user wants to add to the title has to be checked if it is already assigned to another title. So we need a service to search for a title by title.
(p. 52)

### Implementation
```
GET /title?title =<value from view>&_include=id,title&_exclude=_links&media_type=<journal|book|database|other>

{
  data: [{
    id: 42,
    title: "Physics 1"
  }]
}

```
#### Actual Workload:

**Comment by hornmo** [comment]
@dirk-ecker  More specifically, since there is a selection up top for the type of title (Journal, Book, Database), this should really search only in the selected type. So `/journals`, `/books` or `/databases` would be better, unless we want to add that as an additional parameter to a generic `/title` endpoint search (which we will need in addition anyways).

**Comment by dirk-ecker** [comment]
Okay, so we need search capability for resource title and when needed, we add further endpoint for journals, books and databases.

**Comment by hornmo** [comment]
Added in #250 
Endpoint: `/titles?` (use parameter `type=<journal|book|database>` for filtering by type)
The primary label property is `name`.
