### ISSUE TITLE
Problem with "last updated" (Package) for OAI-PMH Request

### ISSUE THREAD

**Issue by darupp** [openlibraryenvironment/gokb#2]
OAI-PMH notices changes on packages by checking "last updated", but this doesn't refresh after a TIPP update, because TIPPs are a class of its own. So Systems using the OAI-PMH API don't get information on changed TIPPs.

Possible solutions:
- Refresh of "last updated" on the package level after a tipp change
- Additional API for TIPP changes as endpoint for OAI-PMH
- Alternative API for TIPPs without OAI-PMH

**Comment by VolkerHBZ** [comment]
Out of the three posible soilutions, i would recommend the first one. Changing just a date on a TIPP doesn't make sense, especially since the TIPPs are considered immutable. A second API endpoint giving "just the same informations like another, BUT:..." seems weird too. Ideally, delivering the correct date would only be an additional clause in the SQL statement.
