### ISSUE TITLE
ElasticSearch: unparseable :

### ISSUE THREAD

**Issue by croqueGrec09** [openlibraryenvironment/gokb#204]
The following package contains ":" in the name: https://phaeton.hbz-nrw.de/gokb/resource/show/89d493cb-cf3b-4a44-845c-f7e64d4c07c3

When I make a search against ES Index, I do not get this package unless I seach exactly for the exact name. This is due to the colons in the package name.
This affects also LAS:eR side package linking since the package does not figure in that list, too.

**Comment by darupp** [comment]
So the ES Index should accept colons, i.e. should not interpret colons as functional characters. @hornmo , can this be fixed?

**Comment by croqueGrec09** [comment]
In LAS:eR, colons are already escaped.

**Comment by hornmo** [comment]
I am assuming your are searching via the parameter `name`? That one only searches for whole words, and since `:` is not defined as a breaking character the only way to find this mislabeled package is by searching for the whole name. It can however be found by searching via the `suggest` parameter, which sounds like what you are looking for anyways:
https://gokb.org/gokb/api/find?componentType=Package&suggest=Wile

As you can see here 
https://gokb.org/gokb/api/find?componentType=Package&name=Wiley
the colon itself is not a problem, but leaving out spaces is.

What should be fixed therefore is the name of the package, since it does not conform to the GOKb data manager package naming guidelines, which demands putting spaces after the colons.

**Comment by croqueGrec09** [comment]
The name is going to be changed.
On the other hand, I do get a default.error.exception when I search for "Wiley: " in the global search.
It may be that it is because of the unparseable colon. I propose code like:
`if(params.q.contains(":") || params.q.contains("-")){`
`sw.write("\"${params.q}\"")`
`}`

**Comment by hornmo** [comment]
Right, this seems to be a bug concerning the global search queries specifically, thanks for pointing that out.
