### ISSUE TITLE
Title deletion by rejectWrongTitles seems not working

### ISSUE THREAD

**Issue by croqueGrec09** [openlibraryenvironment/gokb#238]
Occurred on two different GOKb instances, version 8.6.2

When clearing a package by "Delete (with associated TIPPs)", then clearing by rejectWrongTitles, it is observed that title still remain current. There is no title association by TIPPs, at least, not displayed on title view.
This has the following unnice effects:
- title duplicates
- when uploading a file via Ygor and KBART, identifier match seems arbitrary (creating the TIPP for the wrong title)

**Comment by hornmo** [comment]
This is the intended behavior. The action checks for titles that have no TIPP combos at all, but deleting a TIPP does not delete its link to a title.
Since we concluded there would be no immediate negative consequences in adding those cases, we will adjust the action to include them for now. There will be a review of this further down the road.

**Comment by croqueGrec09** [comment]
The function works as bespoken and expected. Issue is closed!
