### ISSUE TITLE
Merging of title splits in GOKb

### ISSUE THREAD

**Issue by MiriKon** [openlibraryenvironment/gokb#50]
By processing a new KBART file via YGOR - in this case the file for the Beck Hochschulmodul journals
[EZB-HBZBE-01476_hbzKon_beck_2019_05_07.txt](https://github.com/openlibraryenvironment/gokb/files/3152744/EZB-HBZBE-01476_hbzKon_beck_2019_05_07.txt) - an issue has come up with regards to title splits. In the KBART file, the title splits "Bilanzbuchhalter und Controller BC", "BRZ Zeitschrift fuer Bilanzierung und Rechnungswesen" and "BC - Zeitschrift fuer Bilanzierung, Rechnungswesen und Controlling" are listed individually as they should be, yet by uploading the titles as well as the package to the GOKb, these title splits are suddenly "merged" into merely one title, namely "BC - Zeitschrift für Bilanzierung, Rechnungswesen und Controlling". 
This merging of title splits should be avoided in the GOKb if the splits have individual ZDB IDs as in this case where they should be accordingly displayed in the package holdings. I think this might also explain why there is a discrepancy between "Titles/TIPPs (149/155)" in the package holdings https://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.Package%3A391384 ?

The txt-files for the titles and package as processed by YGOR are the following: 

[20190507-1437-EZB-HBZBE-01476_hbzKon_beck_2019_05_07.txt.package (1).txt](https://github.com/openlibraryenvironment/gokb/files/3152809/20190507-1437-EZB-HBZBE-01476_hbzKon_beck_2019_05_07.txt.package.1.txt)
[20190507-1437-EZB-HBZBE-01476_hbzKon_beck_2019_05_07.txt.titles (1).txt](https://github.com/openlibraryenvironment/gokb/files/3152811/20190507-1437-EZB-HBZBE-01476_hbzKon_beck_2019_05_07.txt.titles.1.txt)

**Comment by hornmo** [comment]
It seems to me like all three Journals were correctly matched, though they received different names:
https://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.JournalInstance%3A414104
https://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.JournalInstance%3A414116
https://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.JournalInstance%3A391448

Also, they each have one TIPP, which links them to the package mentioned above.

The discrepancy between the number of unique titles and TIPPs stems from multiple KBART lines having the same ZDB-ID. This is probably due to those titles being "Beihefte", which were not separated in ZDB. As a result, there are duplicate titles in the title JSON generated by YGOR, which result in a single title on import. There are also TIPPs in the package JSON for each of those duplicate lines with different URLs, which result in multiple TIPPs for a single title in GOKb:

2081596-7 -> https://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.JournalInstance%3A391481

2082447-6 -> https://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.JournalInstance%3A391724

**Comment by philboeselager** [comment]
Thanks, @hornmo ! We've found 5 cases of `zdb_id`s that are mentioned twice in the Kbart file. Still in search for the sixth TIPP that makes in difference in the overall count (149 vs. 155).

While investigating the Kbart export of the package mentioned by @MiriKon , I've seen that there are double TIPPs in the export that are only visible one time in the UI / search. E. g.:

https://phaeton.hbz-nrw.de/gokb/search/index?qbe=g%3A3tipps&refOid=org.gokb.cred.Package%3A391384&hide=qp_pkg_id&hide=qp_cp&hide=qp_pkg&hide=qp_pub_id&qp_title=Zeitschrift+fu%CC%88r+Wohnungseigentumsrecht&qp_title_id=&qp_medium=&qp_cp=&qp_pub_id=&qp_pkg_id=391384&qp_pkg=&qp_plat_id=&qp_plat=&qp_status=&qp_onlyCurrent=on&searchAction=search&searchName=

as opposed to two Kbart export lines, only differentiated by the title_id:

- http://beck-online.beck.de/?bcid=Y-300-Z-ZWE
- https://beck-online.beck.de/Dokument?vpath=%2Fbibdata%2Fzeits%2Fzwe%2F2019%2Fcont%2Fzwe.2019.h03.nameinhaltsverzeichnis.htm&anchor=Y-300-Z-ZWE&readable=2

... but only the second one is found in the UI: https://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.JournalInstance%3A392509

Is this an issue or by design?

**Comment by MiriKon** [comment]
Thank you for clearing this up for me! The issue has been moved to https://github.com/hbz/laser-ygor/issues/128 and will be closed here.

**Comment by hornmo** [comment]
@philboeselager the problem here is that those two TIPPs are only differentiated via URL and have the same Platform/Title/Package. Since they came in from two different title import processes, the older of those two TIPPs was immediately retired. 

https://phaeton.hbz-nrw.de/gokb/search/index?qbe=g%3A3tipps&refOid=org.gokb.cred.JournalInstance%3A392509&hide=qp_title_id&hide=qp_title&qp_title=&qp_title_id=392509&qp_medium=&qp_cp=&qp_pub_id=&qp_pkg_id=&qp_pkg=&qp_plat_id=&qp_plat=&qp_status=&qp_onlyCurrent=off&searchAction=search&searchName=

To avoid this problem, we would have to have to let the TIPP upsertDTO function know that another matched TIPP was part of the same package import, and not an earlier state.
